In [1]:
import pandas as pd
import numpy as np

In [2]:
loan_df = pd.read_csv("loan_data_set.csv")

In [3]:
print("Loan Dataset:")
display(loan_df.head())

Loan Dataset:

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [4]:
print("Dataset Information:")
loan_df.info()

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    str
 1   Gender             601 non-null    str
 2   Married            611 non-null    str
 3   Dependents         599 non-null    str
 4   Education          614 non-null    str
 5   Self_Employed      582 non-null    str
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    str
 12  Loan_Status        614 non-null    str
dtypes: float64(4), int64(1), str(8)
memory usage: 62.5 KB

In [5]:
print("Missing Values:")
display(loan_df.isnull().sum())

Missing Values:

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
loan_df["LoanAmount"] = loan_df["LoanAmount"].fillna(loan_df["LoanAmount"].mean())

In [7]:
loan_df["ApplicantIncome"] = loan_df["ApplicantIncome"].fillna(loan_df["ApplicantIncome"].mean())

In [8]:
loan_df["Gender"] = loan_df["Gender"].fillna(loan_df["Gender"].mode()[0])

In [9]:
loan_df["Education"] = loan_df["Education"].fillna(loan_df["Education"].mode()[0])

In [10]:
print("Missing Values After Handling:")
display(loan_df.isnull().sum())

Missing Values After Handling:

Loan_ID               0
Gender                0
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [11]:
print("Basic Statistical Summary:")
display(loan_df.describe())

Basic Statistical Summary:

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,614.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,84.037468,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.250000,360.00000,1.000000
50%,3812.500000,1188.500000,129.000000,360.00000,1.000000
75%,5795.000000,2297.250000,164.750000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [13]:
summary_gender = loan_df.groupby("Gender")["LoanAmount"].agg(
    Mean="mean",
    Median="median",
    Minimum="min",
    Maximum="max",
    Standard_Deviation="std"
)
print("Summary Statistics of LoanAmount grouped by Gender:")
display(summary_gender)

Summary Statistics of LoanAmount grouped by Gender:

              Mean  Median  Minimum  Maximum  Standard_Deviation
Gender
Female  127.225326   114.0      9.0    600.0           78.273015
Male    150.692891   131.5     17.0    700.0           84.752753

In [15]:
summary_education = loan_df.groupby("Education")["ApplicantIncome"].agg(
    Mean="mean",
    Median="median",
    Minimum="min",
    Maximum="max",
    Standard_Deviation="std"
)
print("Summary Statistics of ApplicantIncome grouped by Education:")
display(summary_education)

Summary Statistics of ApplicantIncome grouped by Education:

                     Mean  Median  Minimum  Maximum  Standard_Deviation
Education
Graduate      5857.433333  4000.0      150    81000         6739.797954
Not Graduate  3777.283582  3357.5      210    18165         2237.081586

In [16]:
loan_df["Gender_Numeric"] = loan_df["Gender"].map({"Male": 1, "Female": 0})

In [17]:
gender_numeric_list = loan_df["Gender_Numeric"].tolist()

In [18]:
print("Numeric list for Gender categorical variable:")
print(gender_numeric_list[:20])

Numeric list for Gender categorical variable:
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1]

In [19]:
iris_df = pd.read_csv("iris.csv")

In [20]:
print("Iris Dataset:")
display(iris_df.head())

Iris Dataset:

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [21]:
print("Iris Dataset Information:")
iris_df.info()

Iris Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [22]:
print("Missing Values in Iris Dataset:")
display(iris_df.isnull().sum())

Missing Values in Iris Dataset:

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

In [23]:
print("Statistical Details of Iris Dataset:")
display(iris_df.describe())

Statistical Details of Iris Dataset:

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [27]:
display(iris_df.groupby("sepal.length").describe())

             sepal.width                                                    \
                   count      mean       std  min    25%   50%    75%  max
sepal.length
4.3                  1.0  3.000000       NaN  3.0  3.000  3.00  3.000  3.0
4.4                  3.0  3.033333  0.152753  2.9  2.950  3.00  3.100  3.2
4.5                  1.0  2.300000       NaN  2.3  2.300  2.30  2.300  2.3
4.6                  4.0  3.325000  0.221736  3.1  3.175  3.30  3.450  3.6
4.7                  2.0  3.200000  0.000000  3.2  3.200  3.20  3.200  3.2
4.8                  5.0  3.180000  0.204939  3.0  3.000  3.10  3.400  3.4
4.9                  6.0  2.950000  0.441588  2.4  2.625  3.05  3.100  3.6
5.0                 10.0  3.120000  0.543241  2.0  3.050  3.35  3.475  3.6
5.1                  9.0  3.477778  0.411636  2.5  3.400  3.50  3.800  3.8
5.2                  4.0  3.425000  0.573730  2.7  3.225  3.45  3.650  4.1
5.3                  1.0  3.700000       NaN  3.7  3.700  3.70  3.700  3.7
5.4                  6.0  3.550000  0.350714  3.0  3.400  3.55  3.850  3.9
5.5                  7.0  2.842857  0.723089  2.3  2.400  2.50  3.050  4.2
5.6                  6.0  2.816667  0.194079  2.5  2.725  2.85  2.975  3.0
5.7                  8.0  3.100000  0.656832  2.5  2.750  2.85  3.200  4.4
5.8                  7.0  2.885714  0.494734  2.6  2.700  2.70  2.750  4.0
5.9                  3.0  3.066667  0.115470  3.0  3.000  3.00  3.100  3.2
6.0                  6.0  2.733333  0.471876  2.2  2.325  2.80  2.975  3.4
6.1                  6.0  2.850000  0.151658  2.6  2.800  2.85  2.975  3.0
6.2                  4.0  2.825000  0.492443  2.2  2.650  2.85  3.025  3.4
6.3                  9.0  2.855556  0.400347  2.3  2.500  2.80  3.300  3.4
6.4                  7.0  2.957143  0.207020  2.7  2.800  2.90  3.150  3.2
6.5                  5.0  3.000000  0.141421  2.8  3.000  3.00  3.000  3.2
6.6                  2.0  2.950000  0.070711  2.9  2.925  2.95  2.975  3.0
6.7                  8.0  3.050000  0.250713  2.5  3.000  3.10  3.150  3.3
6.8                  3.0  3.000000  0.200000  2.8  2.900  3.00  3.100  3.2
6.9                  4.0  3.125000  0.050000  3.1  3.100  3.10  3.125  3.2
7.0                  1.0  3.200000       NaN  3.2  3.200  3.20  3.200  3.2
7.1                  1.0  3.000000       NaN  3.0  3.000  3.00  3.000  3.0
7.2                  3.0  3.266667  0.305505  3.0  3.100  3.20  3.400  3.6
7.3                  1.0  2.900000       NaN  2.9  2.900  2.90  2.900  2.9
7.4                  1.0  2.800000       NaN  2.8  2.800  2.80  2.800  2.8
7.6                  1.0  3.000000       NaN  3.0  3.000  3.00  3.000  3.0
7.7                  4.0  3.050000  0.525991  2.6  2.750  2.90  3.200  3.8
7.9                  1.0  3.800000       NaN  3.8  3.800  3.80  3.800  3.8

             petal.length            ...             petal.width            \
                    count      mean  ...    75%  max       count      mean
sepal.length                         ...
4.3                   1.0  1.100000  ...  1.100  1.1         1.0  0.100000
4.4                   3.0  1.333333  ...  1.350  1.4         3.0  0.200000
4.5                   1.0  1.300000  ...  1.300  1.3         1.0  0.300000
4.6                   4.0  1.325000  ...  1.425  1.5         4.0  0.225000
4.7                   2.0  1.450000  ...  1.525  1.6         2.0  0.200000
4.8                   5.0  1.580000  ...  1.600  1.9         5.0  0.200000
4.9                   6.0  2.266667  ...  2.850  4.5         6.0  0.550000
5.0                  10.0  1.840000  ...  1.600  3.5        10.0  0.430000
5.1                   9.0  1.722222  ...  1.700  3.0         9.0  0.400000
5.2                   4.0  2.075000  ...  2.100  3.9         4.0  0.475000
5.3                   1.0  1.500000  ...  1.500  1.5         1.0  0.200000
5.4                   6.0  2.033333  ...  1.700  4.5         6.0  0.516667
5.5                   7.0  3.228571  ...  4.000  4.4         7.0  0.900000
5.6                   6.0  4.200000  ...  4.425  4.9         6.0  1.416667
5.7                   8.0  3.587500  ...  4.275  5.0         8.0  1.100000
5.8                   7.0  4.071429  ...  5.100  5.1         7.0  1.400000
5.9                   3.0  4.700000  ...  4.950  5.1         3.0  1.700000
6.0                   6.0  4.650000  ...  4.950  5.1         6.0  1.500000
6.1                   6.0  4.750000  ...  4.850  5.6         6.0  1.416667
6.2                   4.0  4.750000  ...  4.950  5.4         4.0  1.725000
6.3                   9.0  5.133333  ...  5.600  6.0         9.0  1.811111
6.4                   7.0  5.157143  ...  5.550  5.6         7.0  1.871429
6.5                   5.0  5.240000  ...  5.500  5.8         5.0  1.900000
6.6                   2.0  4.500000  ...  4.550  4.6         2.0  1.350000
6.7                   8.0  5.262500  ...  5.700  5.8         8.0  1.962500
6.8                   3.0  5.400000  ...  5.700  5.9         3.0  1.933333
6.9                   4.0  5.275000  ...  5.475  5.7         4.0  2.050000
7.0                   1.0  4.700000  ...  4.700  4.7         1.0  1.400000
7.1                   1.0  5.900000  ...  5.900  5.9         1.0  2.100000
7.2                   3.0  5.966667  ...  6.050  6.1         3.0  1.966667
7.3                   1.0  6.300000  ...  6.300  6.3         1.0  1.800000
7.4                   1.0  6.100000  ...  6.100  6.1         1.0  1.900000
7.6                   1.0  6.600000  ...  6.600  6.6         1.0  2.100000
7.7                   4.0  6.600000  ...  6.750  6.9         4.0  2.200000
7.9                   1.0  6.400000  ...  6.400  6.4         1.0  2.000000


                       std  min    25%   50%    75%  max
sepal.length
4.3                    NaN  0.1  0.100  0.10  0.100  0.1
4.4           3.399350e-17  0.2  0.200  0.20  0.200  0.2
4.5                    NaN  0.3  0.300  0.30  0.300  0.3
4.6           5.000000e-02  0.2  0.200  0.20  0.225  0.3
4.7           0.000000e+00  0.2  0.200  0.20  0.200  0.2
4.8           7.071068e-02  0.1  0.200  0.20  0.200  0.3
4.9           6.595453e-01  0.1  0.125  0.20  0.800  1.7
5.0           3.267687e-01  0.2  0.200  0.25  0.550  1.0
5.1           2.828427e-01  0.2  0.200  0.30  0.400  1.1
5.2           6.184658e-01  0.1  0.175  0.20  0.500  1.4
5.3                    NaN  0.2  0.200  0.20  0.200  0.2
5.4           4.915960e-01  0.2  0.250  0.40  0.400  1.5
5.5           4.898979e-01  0.2  0.600  1.10  1.250  1.3
5.6           3.125167e-01  1.1  1.300  1.30  1.450  2.0
5.7           5.451081e-01  0.3  0.850  1.25  1.300  2.0
5.8           7.280110e-01  0.2  1.100  1.20  1.900  2.4
5.9           1.732051e-01  1.5  1.650  1.80  1.800  1.8
6.0           2.683282e-01  1.0  1.500  1.55  1.600  1.8
6.1           2.041241e-01  1.2  1.325  1.40  1.400  1.8
6.2           4.349329e-01  1.3  1.450  1.65  1.925  2.3
6.3           4.075673e-01  1.3  1.500  1.80  1.900  2.5
6.4           3.683942e-01  1.3  1.650  1.90  2.150  2.3
6.5           2.645751e-01  1.5  1.800  2.00  2.000  2.2
6.6           7.071068e-02  1.3  1.325  1.35  1.375  1.4
6.7           4.206712e-01  1.4  1.650  1.95  2.325  2.5
6.8           4.725816e-01  1.4  1.750  2.10  2.200  2.3
6.9           3.785939e-01  1.5  1.950  2.20  2.300  2.3
7.0                    NaN  1.4  1.400  1.40  1.400  1.4
7.1                    NaN  2.1  2.100  2.10  2.100  2.1
7.2           4.725816e-01  1.6  1.700  1.80  2.150  2.5
7.3                    NaN  1.8  1.800  1.80  1.800  1.8
7.4                    NaN  1.9  1.900  1.90  1.900  1.9
7.6                    NaN  2.1  2.100  2.10  2.100  2.1
7.7           1.414214e-01  2.0  2.150  2.25  2.300  2.3
7.9                    NaN  2.0  2.000  2.00  2.000  2.0

[35 rows x 24 columns]

In [29]:
print("Mean Values Species-wise:")
display(iris_df.groupby("sepal.length").mean(numeric_only=True))

Mean Values Species-wise:

              sepal.width  petal.length  petal.width
sepal.length
4.3              3.000000      1.100000     0.100000
4.4              3.033333      1.333333     0.200000
4.5              2.300000      1.300000     0.300000
4.6              3.325000      1.325000     0.225000
4.7              3.200000      1.450000     0.200000
4.8              3.180000      1.580000     0.200000
4.9              2.950000      2.266667     0.550000
5.0              3.120000      1.840000     0.430000
5.1              3.477778      1.722222     0.400000
5.2              3.425000      2.075000     0.475000
5.3              3.700000      1.500000     0.200000
5.4              3.550000      2.033333     0.516667
5.5              2.842857      3.228571     0.900000
5.6              2.816667      4.200000     1.416667
5.7              3.100000      3.587500     1.100000
5.8              2.885714      4.071429     1.400000
5.9              3.066667      4.700000     1.700000
6.0              2.733333      4.650000     1.500000
6.1              2.850000      4.750000     1.416667
6.2              2.825000      4.750000     1.725000
6.3              2.855556      5.133333     1.811111
6.4              2.957143      5.157143     1.871429
6.5              3.000000      5.240000     1.900000
6.6              2.950000      4.500000     1.350000
6.7              3.050000      5.262500     1.962500
6.8              3.000000      5.400000     1.933333
6.9              3.125000      5.275000     2.050000
7.0              3.200000      4.700000     1.400000
7.1              3.000000      5.900000     2.100000
7.2              3.266667      5.966667     1.966667
7.3              2.900000      6.300000     1.800000
7.4              2.800000      6.100000     1.900000
7.6              3.000000      6.600000     2.100000
7.7              3.050000      6.600000     2.200000
7.9              3.800000      6.400000     2.000000

In [26]:
print(iris_df.columns)

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='str')

In [31]:
print("Percpentile Details for Iris-setosa:")
display(iris_df[iris_df["sepal.length"] == "Iris-setosa"].describe())

Percpentile Details for Iris-setosa:

       sepal.length  sepal.width  petal.length  petal.width
count           0.0          0.0           0.0          0.0
mean            NaN          NaN           NaN          NaN
std             NaN          NaN           NaN          NaN
min             NaN          NaN           NaN          NaN
25%             NaN          NaN           NaN          NaN
50%             NaN          NaN           NaN          NaN
75%             NaN          NaN           NaN          NaN
max             NaN          NaN           NaN          NaN

In [35]:
print("Percentile Details for Iris-versicolor:")
display(iris_df[iris_df["sepal.length"] == "Iris-versicolor"].describe())

Percentile Details for Iris-versicolor:

       sepal.length  sepal.width  petal.length  petal.width
count           0.0          0.0           0.0          0.0
mean            NaN          NaN           NaN          NaN
std             NaN          NaN           NaN          NaN
min             NaN          NaN           NaN          NaN
25%             NaN          NaN           NaN          NaN
50%             NaN          NaN           NaN          NaN
75%             NaN          NaN           NaN          NaN
max             NaN          NaN           NaN          NaN

In [36]:
print("Percentile Details for Iris-virginica:")
display(iris_df[iris_df["sepal.length"] == "Iris-virginica"].describe())

Percentile Details for Iris-virginica:

       sepal.length  sepal.width  petal.length  petal.width
count           0.0          0.0           0.0          0.0
mean            NaN          NaN           NaN          NaN
std             NaN          NaN           NaN          NaN
min             NaN          NaN           NaN          NaN
25%             NaN          NaN           NaN          NaN
50%             NaN          NaN           NaN          NaN
75%             NaN          NaN           NaN          NaN
max             NaN          NaN           NaN          NaN